### ISSUE TITLE
Add identity cache (always missing)

### ISSUE THREAD

**Issue by vittoriom** [spring-media/Carlos#157]
After discussing with @bkase, it came out that if an identity `CacheLevel` was included in `Carlos`, `CacheLevel` would become a monoid. 
This is an interesting idea that would be worth pursuing.

**Comment by ivanlisovyi** [comment]
We aren't yet sure what we're gonna do with Carlos and where do we see it in the future hence to avoid spreading misinformation about the future development of Carlos I'm closing this issue for now.
