### ISSUE TITLE
why it always occur like this   " No such module PiedPiper ?"

### ISSUE THREAD

**Issue by apiapia** [spring-media/Carlos#164]
i follow below tips step by step,but the repo doesn't work...

To use our Playground, please follow these steps:

    Open the Xcode project Carlos.xcodeproj
    Select the Carlos framework target, and a 64-bit platform (e.g. iPhone 6)
    Build the target with ⌘+B
    Click the Playground file Carlos.playground
    Write your code

**Comment by vittoriom** [comment]
Hi @apiapia, thanks for pointing out this mistake! I believe I missed this paragraph when I updated `Carlos` to include `PiedPiper` as an external dependency. I'll have to update the documentation to use the Playground, will do it in the following days

**Comment by ivanlisovyi** [comment]
Carlos will be migrated from PiedPiper to Combine in the nearest future.
