### ISSUE TITLE
Support for Gloss (Moya)

### ISSUE THREAD

**Issue by YotamGolomb** [spring-media/Carlos#167]
built in support for Gloss Objects (Moya support)

**Comment by vittoriom** [comment]
Hi @YotamGolomb, thanks for your contribution. 
Would you mind elaborating a bit more on what would it mean for you to have support for Gloss (Moya) into Carlos?

Thanks!

**Comment by pietrocaselani** [comment]
Hi @YotamGolomb 
I'm doing a demo projeto using Carlos + Moya + RxSwift.
If I succeed, I post the results and examples here.

**Comment by pietrocaselani** [comment]
@YotamGolomb see if this example works for you https://gist.github.com/pietrocaselani/9b992e00c7615227f8614567249429eb

**Comment by vittoriom** [comment]
Hi @pietrocaselani, thanks for your comment!
Your gist is very interesting, and I'd be even more interested in seeing your demo project. 
It would be great if you could make a pull request with support for Moya or RxSwift, if you had time.

**Comment by ivanlisovyi** [comment]
This issue/feature request seems to be stale. I'm closing it for now.
