### ISSUE TITLE
Minor Compiler Warnings for Swift 4.2

### ISSUE THREAD

**Issue by UncleRic** [spring-media/Carlos#177]
Rebuild with Swift 4.2 to find deprecated warnings.

**Comment by blurtime** [comment]
@vittoriom Will there be any any updates any time soon?

**Comment by vittoriom** [comment]
Hi @blurtime, unfortunately I'm not working on this project anymore. I
agree that it should be migrated to Swift 4.2. In fact, it should receive a
complete overhaul given the new possibilities the language offers now.

It would be great if someone could push a PR for this.

Il giorno sab 15 set 2018 alle ore 20:26 blurtime <notifications@github.com>
ha scritto:
