### ISSUE TITLE
Custom Fetcher with high memory usage

### ISSUE THREAD

**Issue by mufumade** [spring-media/Carlos#191]
Hey 👋  I am currently trying to implement a custom cache fetcher for downloading images from AWS S3 for a SwiftUI image grid like the iOS photo app. 

My fetcher looks like the following: 
```Swift
class S3CacheFetcher: Fetcher {
    
    typealias KeyType = MediaItemCacheInfo
    typealias OutputType = NSData
    
    func get(_ key: KeyType) -> AnyPublisher<OutputType, Error> {
        return download(mediaItem: key).eraseToAnyPublisher()
    }
    
    private func download(mediaItem: KeyType) -> AnyPublisher<OutputType, Error>{
        let BUCKET = "someBucket"
        
        return Deferred {
            Future { promise in
                guard let key:String = S3CacheFetcher.getItemKey(mediaItem: mediaItem) else { fatalError("UserPoolID Error") }
                print("Downloading image with key: \(key)")
                AWSS3TransferUtility.default().downloadData(fromBucket: BUCKET,
                                                            key: key,
                                                            expression: nil) { (task, url, data, error) in
                    if let error = error{
                        print(error)
                        promise(.failure(error))
                    }else if let data = data{
                        if let imageData:Data = S3CacheFetcher.decryptImage(with: data, mediaItem: mediaItem){
                            promise(.success(imageData as NSData))
                        }
                    }
                }
            }
        }
        .eraseToAnyPublisher()
    }
....
}
```
My problem is that when I use only this fetcher without any memory or disk cache than my memory is increasing until the app crashes. I narrowed down the problem to this fetcher because when I am using the included disk cache without my fetcher everything works as expected. The memory usage is around 40-50 Mb and not in the Gb range.

I am fairly new to Combine, so any help is greatly appreciated.

EDIT

My ImageGrid View
```Swift
struct AllPhotos: View {
    @StateObject var mediaManager = MediaManager()
    var body: some View {
      ScrollView{
          LazyVGrid(columns: columns, spacing: 3){
              ForEach(mediaManager.mediaItems) { item in
                  VStack{
                      ImageView(downloader: ImageLoader(mediaItem: item, size: .large, parentAlbum: nil))
                  }
              }
         }
    }
}
```

My ImageView that is shown in each grid item which is responsible to show the image it self
```Swift
struct ImageView: View{
        @StateObject var downloader: ImageLoader
        
        var body: some View {
            Image(uiImage: downloader.image ?? UIImage(systemName: "photo")!)
                .resizable()
                .aspectRatio(contentMode: .fill)
                .onAppear(perform: {
                    downloader.load()
                })
                .onDisappear {
                    downloader.cancel()
                }
        }
    }
```

And the Image loader it self which interacts with the cache.

```Swift
class ImageLoader: ObservableObject {
    @Published var image: UIImage?
    
    private(set) var isLoading = false
    
    private var cancellable: AnyCancellable?
    private(set) var mediaItem:MediaItem
    private(set) var size: ThumbnailSizes
    private(set) var parentAlbum: GetAlbum?
    
    init(mediaItem: MediaItem, size: ThumbnailSizes, parentAlbum: GetAlbum?) {
        self.mediaItem = mediaItem
        self.size = size
        self.parentAlbum = parentAlbum
    }
    
    deinit {
        cancel()
        self.image = nil
    }
    
    func load() {
        guard !isLoading else { return }
        
        cancellable = S3CacheFetcher().get(.init(parentAlbum: self.parentAlbum, size: self.size, cipher: self.mediaItem.cipher, ivNonce: self.mediaItem.ivNonce, mid: self.mediaItem.mid))
            .map{ UIImage(data: $0 as Data)}
            .replaceError(with: nil)
            .handleEvents(receiveSubscription: { [weak self] _ in self?.onStart() },
                          receiveCompletion: { [weak self] _ in self?.onFinish() },
                          receiveCancel: { [weak self] in self?.onFinish() })
            .receive(on: DispatchQueue.main)
            .sink { [weak self] in self?.image = $0 }
    }
    
    func cancel() {
        cancellable?.cancel()
        self.image = nil
    }
    
    private func onStart() {
        isLoading = true
    }
    
    private func onFinish() {
        isLoading = false
    }
}
```

**Comment by ivanlisovyi** [comment]
Hi @mufumade, thank you for reaching us out! 

I guess we need more information about the way your code structure to really understand what's is the problem like: 
1. How big are the images? 
2. From where do you initiated your image downloading requests? Is it in `init` or `onAppear` in your SwiftUI view?
3. Do you cancel redundant requests? 
4. Did you try to limit the memory cache capacity? I believe, by default it's 50MB.

**Comment by mufumade** [comment]
Hey thanks for taking you time for my problem!

1. All images are 500x500 px so not that large
2. See in the updated issue
3. I hope that canceling the publisher is enough?
4. Soo in the updated issue you see that I directly interface with my S3CacheFetcher that's because when the images are already cached on the disk that I do not have a memory issue. I declared the cache static somewhere in my app as well with and without a memory or disk cache  **but when the image has to be downloaded the memory fills up and does not get released.**

I hope you have all the information you need. And thanks again!

**Comment by mufumade** [comment]
@ivanlisovyi I have some updates for you. As you can see am decrypting my images after I downloaded them.
```Swift
 }else if let data = data{
           if let imageData:Data = S3CacheFetcher.decryptImage(with: data, mediaItem: mediaItem){
              promise(.success(imageData as NSData))
           }
 }
```
To Decrypt I am using CryptoKit.AES.GCM.
For some weird reason the memory goes up when I am decrypting data there.

```Swift
....
if let error = error{
    print(error)
    promise(.failure(error))
}else if let data = data{
    
    // Low memory usage
    //promise(.success(data as NSData))
    // ---
    
    // High memory usage
    let encrypt = try! AES.GCM.seal(data, using: S3CacheFetcher.symmetricKey).combined!
    let decrypt = try! AES.GCM.open(AES.GCM.SealedBox(combined: encrypt), using: S3CacheFetcher.symmetricKey)
    promise(.success(decrypt as NSData))
    // ---
}
....
```

I have no idea why.. I am using the `ConditionedOneWayTransformationBox` to decrypt images after the fetching cache level. This seams to work now.

**Comment by ivanlisovyi** [comment]
@mufumade  so, at the point where you resolve the promise you have your image data stored in memory 3 times: original image data you received from S3, encrypted data after `seal` call and decrypted data after `open` call. You can reduce peak memory usage by using `autoreleasepool` 

```swift
autoreleasepool {
    let encrypt = try! AES.GCM.seal(data, using: S3CacheFetcher.symmetricKey).combined!
    let decrypt = try! AES.GCM.open(AES.GCM.SealedBox(combined: encrypt), using: S3CacheFetcher.symmetricKey)
    promise(.success(decrypt as NSData))
}
```

**Comment by mufumade** [comment]
Yes I tried that but the main problem I had is that the memory does not get released. **And by not released I mean for ever.** The memory usage just keeps climbing and climbing. What I would expect is that the memory only holds one image that is shown on the screen and getting released after the image disappears.

**Comment by ivanlisovyi** [comment]
`MemoryCache` will hold up to 50MB indefinitely by default. This is exactly the reason why I've suggested to limit `MemoryCache` capacity in one of my previous comments.
