### ISSUE TITLE
Add an iCloud CacheLevel

### ISSUE THREAD

**Issue by vittoriom** [spring-media/Carlos#66]
This CacheLevel would use `NSUbiquitousKeyValueStore` and would only be used for unfrequent and small changes
- [ ] Investigate whether it's possible to have an iCloud domain (similar to the NSUserDefaults case) - needed to safely clear the contents of the cache
- [ ] Define a protocol for all the types that can be saved to iCloud
- [ ] Implement get, set, clear, onMemoryWarning
- [ ] Add code documentation
- [ ] Add tests
- [ ] Add sample code
- [ ] Update README.md
- [ ] Update Wiki
- [ ] Update CHANGELOG.md
- [ ] Update Github milestone

**Comment by ivanlisovyi** [comment]
We aren't yet sure what we're gonna do with Carlos and where do we see it in the future hence to avoid spreading misinformation about the future development of Carlos I'm closing this issue
