### ISSUE TITLE
Add an image resizing output transformer

### ISSUE THREAD

**Issue by vittoriom** [spring-media/Carlos#69]
- [ ] Implement image resizing algorithm
- [ ] Create ImageResizer that can be used as an output transformer
- [ ] Consider changing CacheProvider to use the image resizer
- [ ] Write tests
- [ ] Write code documentation
- [ ] Add sample code
- [ ] Update README.md
- [ ] Update Wiki
- [ ] Update CHANGELOG.md
- [ ] Update Github milestone

**Comment by ivanlisovyi** [comment]
We aren't yet sure what we're gonna do with Carlos and where do we see it in the future hence to avoid spreading misinformation about the future development of Carlos I'm closing this issue. Also this issue has not been updated since 4 years ago and I would consider it stale.
