### ISSUE TITLE
Add a Plist value transformer and cache

### ISSUE THREAD

**Issue by vittoriom** [spring-media/Carlos#74]
- [ ] Basic API
- [ ] Implement plist parser so that it can be used as a value transformer
- [ ] Add a plistCache function to CacheProvider
- [ ] Write tests
- [ ] Write code documentation
- [ ] Add sample code
- [ ] Update README.md
- [ ] Update Wiki
- [ ] Update CHANGELOG.md
- [ ] Update Github milestone

**Comment by ivanlisovyi** [comment]
We aren't yet sure what we're gonna do with Carlos and where do we see it in the future hence to avoid spreading misinformation about the future development of Carlos I'm closing this issue. Also this issue has not been updated since 4 years ago and I would consider it stale.
