### ISSUE TITLE
Make it possible to chain cache levels

### ISSUE THREAD

**Issue by vittoriom** [spring-media/Carlos#93]
wrt to #15 and #16, first a vision should be defined for transformers and cache levels and then this issue should be implemented.

E.g.
A transformer closure right now looks exactly the same as the get method of a CacheLevel/Fetcher.
The latter has other methods, though (set, clear, onMemoryWarning).
A transformer/transformer closure could be wrapped into a Fetcher (CacheLevel) and then the key transformation API could be merged with the cache chaining API.
Value transformation / output post-processing API could also be merged and included in the cache chaining API, so that the latter could be the final stage of the async composition applied to caches.
- [ ] Define basic API
- [ ] Implement protocol extension / operator
- [ ] Consider unifying the API (transformers and cache levels are very similar at the moment)
- [ ] Write tests
- [ ] Write code documentation
- [ ] Add sample code
- [ ] Update README.md
- [ ] Update Wiki
- [ ] Update CHANGELOG.md
- [ ] Update Github milestone

**Comment by ivanlisovyi** [comment]
We aren't yet sure what we're gonna do with Carlos and where do we see it in the future hence to avoid spreading misinformation about the future development of Carlos I'm closing this issue for now.
